### PR TITLE
Middleware for static files

### PR DESCRIPTION
**Pull request by joaoduarte19**
The static file server that was at the core of TMVCEngine has been moved to TMVCStaticFilesMiddleware middleware.

We need to define whether the `DocumentRoot`, `IndexDocument` and `FallbackResource` settings should continue in TMVCEngine.Config or whether they will become exclusive to this Middleware.

### CODE REVIEW

**Comment by danieleteti** [comment]
`IndexDocument` isn't used anymore.
`DocumentRoot` and `FallbackResource` should be Middleware constructor parameters with sensibile defaults (e.g.  `IndexDocument` = `index.html` and `FallbackResource` = `index.html`).

However, I'd like to rename the `FallbackResource` to `IndexDocument`. What do you think about?

**Comment by danieleteti** [comment]
Moreover, I'd like to map only a specific url path to the static file. That path can be also empty (e.g. `/`). There can be more than one static middleware plugged in a `TMVCEngine`.

So, the very first lines of code in the OnBeforeRouting should be something like:

```delphi
  if SameText(AContext.Request.PathInfo, fStaticFilePath) then
  begin
    //other code
  end;
```

The idea is to don't ask to the OS if a file exists at every request, but only for requests having a compatibile URI segment.

You agree?

**Comment by joaoduarte19** [comment]
> `IndexDocument` isn't used anymore.
> `DocumentRoot` and `FallbackResource` should be Middleware constructor parameters with sensibile defaults (e.g. `IndexDocument` = `index.html` and `FallbackResource` = `index.html`).
> 
> However, I'd like to rename the `FallbackResource` to `IndexDocument`. What do you think about?

That's how I thought, pass these settings as parameters in the middleware contructor. 
In the TMVCBaseViewEngine class I found that it makes use of the DocumentRoot configuration. Should we remove it from there?
I think renaming `FallbackResource` to `IndexDocument` is a good choice.

**Comment by joaoduarte19** [comment]
> Moreover, I'd like to map only a specific url path to the static file. That path can be also empty (e.g. `/`). There can be more than one static middleware plugged in a `TMVCEngine`.
> 
> So, the very first lines of code in the OnBeforeRouting should be something like:
> 
> ```pascal
>   if SameText(AContext.Request.PathInfo, fStaticFilePath) then
>   begin
>     //other code
>   end;
> ```
> 
> The idea is to don't ask to the OS if a file exists at every request, but only for requests having a compatibile URI segment.
> 
> Do you agree?

That's a very interesting idea. 
With this I could, for example, have multiple versions of my static files on the same server.
I agree it will be a great resource.

**Comment by danieleteti** [comment]
> In the TMVCBaseViewEngine class I found that it makes use of the DocumentRoot configuration. Should we remove it from there?

Yes, it is "fallback" mechanism which I don't like anymore. Views *must* be in the `ViewPath` folder, not in the `DocumentRoot`.

We can remove this block of code in `MVCFramework.pas`:

```
  if not TFile.Exists(F) then
    FileName := ExpandFileName(IncludeTrailingPathDelimiter(GetApplicationFileNamePath +
      Config.Value[TMVCConfigKey.DocumentRoot]) + FileName)
  else
    FileName := F;

```

**Comment by joaoduarte19** [comment]
That's right! So I will continue with the development following these suggestions.

**Comment by joaoduarte19** [comment]
Hi Daniele, the middleware is already working with the latest requirements that we talked about. If that's the case, it's almost finished, we just need to adjust the examples that make use of static files.

**Comment by joaoduarte19** [comment]
I thought we'd add an AfterRouting method to the middleware, to run after all the server actions. Currently the AfterControllerAction method runs only if the action is performed by a controller, if the action is performed by a middleware I cannot do anything after this execution. An example of using this method will be in the Etag middleware that needs to generate the Etag for any response.
What do you think of this idea?

**Comment by danieleteti** [comment]
Yes, it can make sense. However, we have to know which action has been called (if any).

**Comment by joaoduarte19** [comment]
> Yes, it can make sense. However, we have to know which action has been called (if any).

In commit 87db1f09a5534222f41c3a2a5fdbcab49eb043f9 I added the OnAfterRouting method to IMVCMiddleware. However I did not understand the need to know what was the action called in this method.

**Comment by danieleteti** [comment]
No real cases for now, itsy just an info that you'd like to have. 

What happen if an action raises some exception? Does the OnAfterRouting be called? Does it should? If yes (as I think) I would like to know which action raises that error. Or perhaps I just need to know if an action has been called. What's you thought about it?

**Comment by joaoduarte19** [comment]
> What happen if an action raises some exception? 

AfterRouting will be executed even if there are any exceptions.

> I would like to know which action raises that error. Or perhaps I just need to know if an action has been called. What's you thought about it?

I think that in the OnAfterRouting method we only need to know if any actions have been taken. When we want to know what action was performed we use the OnAfterControllerAction method.

**Comment by danieleteti** [comment]
Yes, It makes sense. Go for it.

**Comment by joaoduarte19** [comment]
After several tests I think the job is done.

In summary, the changes made were:
- The static file server has been removed from the TMVCEngine core and has been added to TMVStaticFilesMiddleware;
- The `DocumentRoot` and `FallbackResource` settings have been removed from TMVCEngine.Config and become exclusive to Static File Middleware. `FallbackResource` has been renamed to `IndexDocument`
- Support for adding multiple TMVCStaticFilesMiddleware mapped from different URL paths has been added;
- Etag Middleware has been added ([RFC 7232](https://tools.ietf.org/html/rfc7232#section-2.3))
- The OnAfterRouting method was added to the IMVCMiddleware interface.
- All examples have been changed to suit the new changes

**Pull request merged**
