### PR TITLE
New restclient

### PR DESCRIPTION
**Pull request by joaoduarte19**
Hi @danieleteti,

I encapsulated the delphi REST Client library in a TRESTClient class for ease of use.
I am already using this class in personal projects, and I would like to integrate it with the DMVC replacing the current TRESTClient, which has some limitations.
Do you think this is a good idea? If so, I will make further improvements and implement unit tests, to make it even more compatible with the DMVC project.
As some methods are different in this new RESTClient unit, I thought about renaming the old MVCFramework.RESTClient unit to MVCFramework.RESTClient.Indy.

Here is a simple example of using the new RESTClient:
```delphi
var
  lRESTREsponse: IRESTResponse;
begin
  lRESTREsponse := TRESTClient.New
    .BaseURL('http://localhost:8080')
    .SetBasicAuthorization('username', 'password')
    .Post('/login');
```

### CODE REVIEW

**Comment by danieleteti** [comment]
Hi, this is a very good idea. Was in the roadmap a major "refurbish" of the TMVCRESTClient based on Indy. Now, unittest shiykld be done and the currentunittest and samples should be migrated to the new restclient. It's a bit of work, but if we start from the restclient unittest itself, the subsequents should be simpler. Also, if the interface is not 100% compatible I would avoid to use the same unit name because this could cause confusion.

**Comment by joaoduarte19** [comment]
> Good Job @joaoduarte19
> 
> When you think will be ready?

It will be ready soon. I'm working on unit tests right now.

**Comment by joaoduarte19** [comment]
Hi @danieleteti 
I believe that at this moment the new RESTClient is ready to be used.
I converted unit tests to use it. I tested using Delphi 10.3 Rio.

## Usage examples:
```delphi
var  
  lClient: IMVCRESTClient;
  lResponse: IMVCRESTResponse;
begin
  // Basic login example
  lClient := TMVCRESTClient.Create;
  lResponse := lClient
    .BaseURL('http://localhost:8080')
    .SetBasicAuthorization('username', 'password')
    .Post('/login');

  // Use of path params
  lResponse := TMVCRestClient.New
    .BaseURL('localhost', 8080)
    .Accept('application/json')
    .AcceptCharset('utf-8')
    .AcceptEncoding('gzip')
    .AddPathParam('Param1', 1)
    .AddPathParam('Param2', 'DMVCFramework')    
    .Get('/req-with-params/($Param1)/{Param2}');

end;  
```

The only limitation of this new RESTClient compared to the RESTClient based on Indy is that it only accepts compressed responses as gzip. This is a limitation of delphi's RESTClient. I opened a request for deflate support, see the ticket 
[RSP-30486](https://quality.embarcadero.com/browse/RSP-30486)

**Comment by danieleteti** [comment]
Great! Did you tested the samples too?

**Comment by joaoduarte19** [comment]
> Great! Did you tested the samples too?

I started testing the samples. Soon I finish.

**Comment by joaoduarte19** [comment]
All samples that used TRESTClient have been changed to use TMVCRESTClient.

The old RESTClient (based on Indy) continues to function normally, only the deprecated warning has been added.

All tests were done using Delphi Rio, but I believe that in the other versions it will work without problems.

**Pull request merged**
