### PR TITLE
Issue #552 - New improvements in Active Record for use with fields of primary key of kind Guid;

### PR DESCRIPTION
**Pull request by marcelojaloto**
See more in issue #552.

**Notes:** 
Pending PR from issue #546.

### CODE REVIEW

**Comment by danieleteti** [comment]
Does these changes pass unit tests?

**Comment by marcelojaloto** [comment]
@danieleteti Yes, all tests passed.

image

**Comment by marcelojaloto** [comment]
@danieleteti,
It is ok?

**Review by danieleteti — COMMENTED** [review]
Where is gone this check?

https://github.com/danieleteti/delphimvcframework/pull/554/files#diff-63305e10dae56ab0498e0758110b65e885fec0d6e8dbd2e92d4eae5665a6ccdbL2151

**Comment by marcelojaloto** [comment]
> Where is gone this check?
> 
> https://github.com/danieleteti/delphimvcframework/pull/554/files#diff-63305e10dae56ab0498e0758110b65e885fec0d6e8dbd2e92d4eae5665a6ccdbL2151

@danieleteti 

Has been moved to a new overload.

image

**Comment by marcelojaloto** [comment]
All overload methods LoadByPk are synchronized in this overload (image above) for code reuse.

**Comment by danieleteti** [comment]
> All overload methods LoadByPk are synchronized in this overload (image above) for code reuse.

Good! I didn't see that. Thank you. I'll do the merge ASAP.

**Comment by danieleteti** [comment]
I'm doing the merge. Are there the unit tests cases you did?

**Comment by marcelojaloto** [comment]
> I'm doing the merge. Are there the unit tests cases you did?

Yes, are there.
I tested with default unit tests from DMVC.
I sent for you 20 days ago a image with the report of all test ok completed.

**Comment by danieleteti** [comment]
> > I'm doing the merge. Are there the unit tests cases you did?
> 
> Yes, are there. I tested with default unit tests from DMVC. I sent for you 20 days ago a image with the report of all test passed ok.

OK, I know. I'm talking about specific test for this new feature, not the old ones.

**Comment by marcelojaloto** [comment]
> > > I'm doing the merge. Are there the unit tests cases you did?
> > 
> > 
> > Yes, are there. I tested with default unit tests from DMVC. I sent for you 20 days ago a image with the report of all test passed ok.
> 
> OK, I know. I'm talking about specific test for this new feature, not the old ones.

Yes, too.

**Comment by danieleteti** [comment]
Sorry @marcelojaloto maybe I'm in "pre-holiday" mode :-) but I don't find the unit test in your changed file.

image

Can you help me to find them?

**Comment by marcelojaloto** [comment]
@danieleteti I didn't create new tests units files. I only runned existing DMVC units tests and all tests passed with ok.

**Comment by marcelojaloto** [comment]
@danieleteti thanks for new unit tests! 😁

Uses uuid type field in the PostgreSQL in the primary Key for a better performance, and Delphi field type uses TGUID as sample below.

Tablet sample in PostgreSQL:

CREATE TABLE public.groups (
	id uuid NOT NULL,
	name varchar(30) NOT NULL
	CONSTRAINT groups_pk PRIMARY KEY (id)
);

  [MVCNameCase(ncLowerCase)]
  [MVCTable('groups')]
  TCustomerWithGUID = class(TActiveRecord)
  private
    [MVCTableField('id', [foPrimaryKey])]
    fID: TGUID;
    [MVCTableField('name')]
    fName: String;
  public
    property ID: TGUID read fGUID write fGUID;
    property Name: String read fName write fName;
  end;

Notes:
When necessary you can to convert a field TGUID into a String, but don't use String types in the field of a class.

Don't uses nullable types for a primary key field because in the database tablet this one it is a field "not null".

**Pull request merged**
