### PR TITLE
New features: addition MVCFramework.Server.pas with MVCServer, MVCDefaultSecurity and MVCServerContainer

### PR DESCRIPTION
**Pull request by ezequieljuliano**
The creation of the MVC server was facilitated. In addition you can add in a container an unlimited number of servers in a single application.

The new unit is called MVCFramework.Server.pas.

It was added unit testing and a small example.

### CODE REVIEW

**Comment by danieleteti** [comment]
Thank you ezequieljuliano!
Does this update introduce some breaking changes? Does invalidate current servers?

**Comment by ezequieljuliano** [comment]
These changes do not invalidate the current servers.
It is a totally separate configuration.

**Comment by danieleteti** [comment]
Great! Thank you.

**Comment by danieleteti** [comment]
ezequieljuliano, could you provide in the wiki a small tutorial or summary about your new changes?

**Comment by ezequieljuliano** [comment]
Yes. Can I add directly to README.md?

**Comment by danieleteti** [comment]
OK

**Comment by ezequieljuliano** [comment]
I created a new Pull Request with the tutorial

**Comment by danieleteti** [comment]
How these changes affect the apache module and the ISAPI dll development? The multi server containers works as well?

**Comment by ezequieljuliano** [comment]
I did not get to test the model with ISAPI DLL. But I believe that the container be in the DLL context no problem. 

But it's good to test. Do you have a tutorial or documentation that explains how to set up an Apache server with ISAPI DLL?

**Comment by danieleteti** [comment]
Check the mod_apache sample

**Comment by danieleteti** [comment]
In the meantime I changed the readme.md to be clear about the support.

**Comment by ezequieljuliano** [comment]
I studied the Apache module. And these features simplified creation server and server container only works in stand alone mode, as you put in README.md.

**Comment by ezequieljuliano** [comment]
I think it would be interesting you create a sub-domain with a wiki. Thus, it is possible to explain step by step how to use and that serves each of the framework functionality.

**Comment by danieleteti** [comment]
Yes, I think so...
I'd like to use the github pages or http://sphinx-doc.org/

**Pull request merged**
