### PR TITLE
Serializer improvements

### PR DESCRIPTION
**Pull request by joaoduarte19**
I'm starting to use the new version of [Spring4D](https://bitbucket.org/sglienke/spring4d/src/develop/) (branch develop) and I noticed that the Collections have RTTI turned off, so the serializer is unable to map the methods through the TDuckTypedList. To get around this I added the possibility to create custom serializers for Collections.

With this change, any collection that cannot be mapped by TDuckTypedList can be serialized through a custom serializer.

### CODE REVIEW

**Comment by danieleteti** [comment]
Why the current approach regarding custom type serializers doesn't work? Also, the lack of RTTI in Spring4D collections will remain also in the release or is only the "working version" which doen't contains enough RTTI info?

**Comment by joaoduarte19** [comment]
> Why the current approach regarding custom type serializers doesn't work? 

Currently the serializer checks to see if there is a custom serializer for the type using the SerializeObject or DesserializeObject method. Even if I change all calls from SerializeCollection/DesserializeCollection to SerializeObject/DesserializeObject, when I pass a JsonArray in DesserializeObject an exception is thrown.
Another flaw I found when serializing class properties is that the search for a custom serializer is done by the type of the property and not by the type actually instantiated in that property. So for properties that are classes or interfaces I modified it to look for custom serializers by the instantiated type.
Avoiding breaking the entire code base, I chose to insert the custom serializer checks in the collection serialization methods.

> Also, the lack of RTTI in Spring4D collections will remain also in the release or is only the "working version" which doen't contains enough RTTI info?

From what was answered by the maintainer at https://bitbucket.org/sglienke/spring4d/issues/320/regression-rtti-information-is-missing-in, the RTTI information for lists will remain off after the release of version 2.0 of Spring4D.
As I use Spring4D in my projects and I believe that many other users also use it in conjunction with DMVC, I decided to propose these adaptations, in addition to inserting an example of a custom serializer for the Spring 2.0 collections

**Comment by danieleteti** [comment]
Hi @joaoduarte19 , all the unit tests are green with this change?

**Comment by joaoduarte19** [comment]
> Hi @joaoduarte19 , all the unit tests are green with this change?

Yes, all unit tests pass this change

**Comment by sglienke** [comment]
FWIW the way serializers are identified is very limiting - using the TypeInfo as a key in a dictionary limits them wrt to generics. A better approach would be to have some kind of `CanHandle` function on the custom serializers passing in a TValue so it can not only handle one specific typeInfo but determine if it can handle whatever is inside that TValue.

As with the TSpringListSerializer the approach this is just asking to fall apart or not work properly. Assuming certain implementation details from the Spring.Collections.* units that contain the implementing classes is just asking for this to break the next time some internals are being changed. When I removed the RTTI I took care of offering ways for serialization offering the `ICollection` interface and deserialization by offering the non-generic `TCollections.CreateObjectList` function where you can pass in the elementType for the list to be created.

**Comment by Ravaut123** [comment]
I was looking how to serialize IList from Spring with MVC

`unit Test.Serializer;

interface

uses
  DUnitX.TestFramework,
  SixBrain;

type
  [TestFixture]
  TSerializerTest = class
  public
    [Test]
    procedure JsonToCollection();

  end;

  TPerson = class (TInterfacedObject)
  private
    fLastName: String;
    fFirstName: String;

  public
    property FirstName: String read fFirstName write fFirstName;
    property LastName: String read fLastName write fLastName;
  end;


implementation

uses
  Spring.Collections,
  Spring.Collections.Lists,
  MVCFramework.Serializer.Intf,
  MVCFramework.Serializer.JsonDataObjects,
  Test.Serializer.CustomTypes;


procedure TSerializerTest.JsonToCollection;
begin
  var strJson: string := '[{"FirstName": "Richardo", "LastName": "The killer" }, {"FirstName": "Zorro", "LastName": "Z-Man" }]';
  var oPersons : IList<TPerson> := TCollections.CreateObjectList<TPerson> ;
  var lSerializer: IMVCSerializer := TMVCJsonDataObjectsSerializer.Create;
  lSerializer.RegisterTypeSerializer(TypeInfo(TFoldedList<System.TObject>), TListSerializer.Create);
  lSerializer.DeserializeCollection(strJson, oPersons, TPerson);
  Assert.AreEqual(oPersons[0].FirstName , 'Richardo');
  Assert.AreEqual(oPersons[1].FirstName , 'Zorro');
end;

initialization
  TDUnitX.RegisterTestFixture(TSerializerTest);

end.`



And the TListSerializer code

`unit Test.Serializer.CustomTypes;

interface

uses
  System.SysUtils,
  System.Rtti,
  MVCFramework.Commons,
  MVCFramework.Serializer.Intf,
  MVCFramework.Serializer.Commons;



type
  // Custom serializer
  TListSerializer = class(TInterfacedObject, IMVCTypeSerializer)
  public
    procedure SerializeAttribute(const AElementValue: TValue; const APropertyName: string;
      const ASerializerObject: TObject; const AAttributes: System.TArray<System.TCustomAttribute>);
    procedure SerializeRoot(const AObject: TObject; out ASerializerObject: TObject;
      const AAttributes: System.TArray<System.TCustomAttribute>;
      const ASerializationAction: TMVCSerializationAction = nil);
    procedure DeserializeAttribute(var AElementValue: TValue; const APropertyName: string;
      const ASerializerObject: TObject; const AAttributes: System.TArray<System.TCustomAttribute>);
    procedure DeserializeRoot(const ASerializerObject: TObject; const AObject: TObject;
      const AAttributes: System.TArray<System.TCustomAttribute>);
  end;



implementation
uses
  System.TypInfo,
  Spring.Collections,
  MVCFramework.Serializer.JsonDataObjects,
  JsonDataObjects;

{ TListSerializer }

procedure TListSerializer.DeserializeAttribute(var AElementValue: TValue; const APropertyName: string; const ASerializerObject: TObject;
  const AAttributes: System.TArray<System.TCustomAttribute>);
begin
//
end;

procedure TListSerializer.DeserializeRoot(const ASerializerObject, AObject: TObject; const AAttributes: System.TArray<System.TCustomAttribute>);
var
  cColl: ICollection;
  lJSONArr: TJDOJsonArray;
  intloop: Integer;
  Obj: TObject;
  ctx: TRttiContext;
  rType: TRttiType;
  lSerializer: IMVCSerializer;
begin
  lSerializer := TMVCJsonDataObjectsSerializer.Create;
  if assigned(AObject) then
  begin
     if Supports(AObject, GetTypeData(TypeInfo(ICollection))^.Guid, cColl) then
     begin
       ctx := TRttiContext.Create;
       rType := ctx.GetType(cColl.ElementType);
       lJSONArr := (ASerializerObject as TJDOJsonArray);
       for intloop := 0 to lJSONArr.Count-1 do
       begin
         Obj := TMVCSerializerHelper.CreateObject(rType.AsInstance.MetaclassType.QualifiedClassName);
         lSerializer.DeserializeObject(lJSONArr.Items[intloop].ObjectValue.ToString, Obj);
         cColl.Add(Obj);
       end;
     end;
  end;
end;

procedure TListSerializer.SerializeAttribute(const AElementValue: TValue; const APropertyName: string; const ASerializerObject: TObject;
  const AAttributes: System.TArray<System.TCustomAttribute>);
begin
//
end;

procedure TListSerializer.SerializeRoot(const AObject: TObject; out ASerializerObject: TObject; const AAttributes: System.TArray<System.TCustomAttribute>;
  const ASerializationAction: TMVCSerializationAction);
begin
//
end;

end.`

**Pull request merged**
