### PR TITLE
Added Swagger support

### PR DESCRIPTION
**Pull request by joaoduarte19**
- TMVCSwaggerMiddleware was created to generate API Swagger documentation.
- Added the .\samples\swaggerdoc example that contains the use of TMVCSwaggerMiddleware and its attributes.

The basic documentation is already generated. More features are still under development.

**[SwagDoc](https://github.com/marcelojaloto/SwagDoc) library required to generate documentation**

### CODE REVIEW

**Comment by joaoduarte19** [comment]
Still need to add
- JsonSchemas generation for documentation
- Authentication Settings

**Comment by joaoduarte19** [comment]
Api swagger documentation generation is done

**Comment by danieleteti** [comment]
@joaoduarte19 thank you for your great work, much appreciated.

Hower I'm finding some problem to add swagger documentation fo the articles_crud server in the samples folder. Seems that the different HTTP verbs are not correctly aggregated in the swagger.json file, but generates more json property with the same name. This raise an exception in the Swagger UI. Can you check on your side please?

**Comment by joaoduarte19** [comment]
I will check ASAP

**Comment by joaoduarte19** [comment]
Bug fixed

**Pull request merged**
