### PR TITLE
TMVCJWTAuthenticationMiddleware.Create #259

### PR DESCRIPTION
**Pull request by viniciussanchez**
Improvements implemented....

### CODE REVIEW

**Comment by viniciussanchez** [comment]
?

**Comment by danieleteti** [comment]
I think that this PR changes the behavior of the implementation to a more strict, and not standard, way. If I correctly understood, some of the claims become mandatory while they are not.


For example, the current code makes the `nbf` claims optional.
```delphi
 if TJWTCheckableClaim.NotBefore in RegClaimsToChecks then
begin
  if not CheckNotBefore(Payload, Error) then
  begin
     Exit(False);
  exit;
end;
```

The PR makes `nbf` mandatory, and this is not adheering with the standard.

Did I correnbtly understood?

Also, please consider these suggestions:
- use `begin..end` also for the single line block in `if`, `while`, `for` and so on. This is the standard used in the code base.
- Use one PR for one change. If a PR contains more than 1 (functional) change I'm can only accept all or nothing, which is not good.

Thank you

**Comment by viniciussanchez** [comment]
> Did I correnbtly understood?
**Not...** `nbf` is validated only if it is contained in the token.
Today I have to put him in the token, and still inform that I want him to validate him.
Why do I have to inform you that I want him to validate it, since I already put it or someone put it in the token with this intuition?
What I implemented was an intelligence check, has `nbf` in the token? So valid ... Don't you? So it's not required ...

Thanks for the suggestions...

**Comment by danieleteti** [comment]
Ah, now I understood your POV :-). Your solution would be correct if the token would be generated only by your server. But the jwt could be generated also by another server. So you *must* check that it contains all the required claimns for *your* server. You cannot blindly suppose that the token has been generated by you.

**Comment by viniciussanchez** [comment]
Got it...
I will send a separate PR then for "Added QueryParams property of type TDictionary <string, string> like ContentFields property" and one for "Render overload". Can be?

**Comment by danieleteti** [comment]
The Render overload has been implemented and will be pushed within today. You can push a single PR for the QueryParams as Dictionary. Thank you.

**Pull request closed without merging**
